#! /bin/bash
nmcli --terse --fields DEVICE dev status|grep -v "eth0"|grep -v "lo">CARD
wireless=$(awk {'print$1'} < test.txt) 
sudo ifconfig $wireless down
sudo iwconfig $wireless mode monitor
sudo ifconfig $wireless up
